# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb",
         "Deck": "01_deck.ipynb"}

modules = ["card.py"]

doc_url = "https://ray0727.github.io/deck_of_cards/deck_of_cards/"

git_url = "https://github.com/ray0727/deck_of_cards/tree/master/"

def custom_doc_links(name): return None
