# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ray0727.github.io/nbtest1/"

git_url = "https://github.com/ray0727/nbtest1/tree/master/"

def custom_doc_links(name): return None
